package it.aesposito.jstore.bean;

import java.util.ArrayList;
import java.util.List;

public class ApplicationPropertiesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public ApplicationPropertiesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeIsNull() {
            addCriterion("ragione_sociale is null");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeIsNotNull() {
            addCriterion("ragione_sociale is not null");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeEqualTo(String value) {
            addCriterion("ragione_sociale =", value, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeNotEqualTo(String value) {
            addCriterion("ragione_sociale <>", value, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeGreaterThan(String value) {
            addCriterion("ragione_sociale >", value, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeGreaterThanOrEqualTo(String value) {
            addCriterion("ragione_sociale >=", value, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeLessThan(String value) {
            addCriterion("ragione_sociale <", value, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeLessThanOrEqualTo(String value) {
            addCriterion("ragione_sociale <=", value, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeLike(String value) {
            addCriterion("ragione_sociale like", value, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeNotLike(String value) {
            addCriterion("ragione_sociale not like", value, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeIn(List<String> values) {
            addCriterion("ragione_sociale in", values, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeNotIn(List<String> values) {
            addCriterion("ragione_sociale not in", values, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeBetween(String value1, String value2) {
            addCriterion("ragione_sociale between", value1, value2, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeNotBetween(String value1, String value2) {
            addCriterion("ragione_sociale not between", value1, value2, "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andPivaCfIsNull() {
            addCriterion("piva_cf is null");
            return (Criteria) this;
        }

        public Criteria andPivaCfIsNotNull() {
            addCriterion("piva_cf is not null");
            return (Criteria) this;
        }

        public Criteria andPivaCfEqualTo(String value) {
            addCriterion("piva_cf =", value, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfNotEqualTo(String value) {
            addCriterion("piva_cf <>", value, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfGreaterThan(String value) {
            addCriterion("piva_cf >", value, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfGreaterThanOrEqualTo(String value) {
            addCriterion("piva_cf >=", value, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfLessThan(String value) {
            addCriterion("piva_cf <", value, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfLessThanOrEqualTo(String value) {
            addCriterion("piva_cf <=", value, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfLike(String value) {
            addCriterion("piva_cf like", value, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfNotLike(String value) {
            addCriterion("piva_cf not like", value, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfIn(List<String> values) {
            addCriterion("piva_cf in", values, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfNotIn(List<String> values) {
            addCriterion("piva_cf not in", values, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfBetween(String value1, String value2) {
            addCriterion("piva_cf between", value1, value2, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andPivaCfNotBetween(String value1, String value2) {
            addCriterion("piva_cf not between", value1, value2, "pivaCf");
            return (Criteria) this;
        }

        public Criteria andIndirizzoIsNull() {
            addCriterion("indirizzo is null");
            return (Criteria) this;
        }

        public Criteria andIndirizzoIsNotNull() {
            addCriterion("indirizzo is not null");
            return (Criteria) this;
        }

        public Criteria andIndirizzoEqualTo(String value) {
            addCriterion("indirizzo =", value, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoNotEqualTo(String value) {
            addCriterion("indirizzo <>", value, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoGreaterThan(String value) {
            addCriterion("indirizzo >", value, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoGreaterThanOrEqualTo(String value) {
            addCriterion("indirizzo >=", value, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoLessThan(String value) {
            addCriterion("indirizzo <", value, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoLessThanOrEqualTo(String value) {
            addCriterion("indirizzo <=", value, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoLike(String value) {
            addCriterion("indirizzo like", value, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoNotLike(String value) {
            addCriterion("indirizzo not like", value, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoIn(List<String> values) {
            addCriterion("indirizzo in", values, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoNotIn(List<String> values) {
            addCriterion("indirizzo not in", values, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoBetween(String value1, String value2) {
            addCriterion("indirizzo between", value1, value2, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andIndirizzoNotBetween(String value1, String value2) {
            addCriterion("indirizzo not between", value1, value2, "indirizzo");
            return (Criteria) this;
        }

        public Criteria andCapIsNull() {
            addCriterion("cap is null");
            return (Criteria) this;
        }

        public Criteria andCapIsNotNull() {
            addCriterion("cap is not null");
            return (Criteria) this;
        }

        public Criteria andCapEqualTo(String value) {
            addCriterion("cap =", value, "cap");
            return (Criteria) this;
        }

        public Criteria andCapNotEqualTo(String value) {
            addCriterion("cap <>", value, "cap");
            return (Criteria) this;
        }

        public Criteria andCapGreaterThan(String value) {
            addCriterion("cap >", value, "cap");
            return (Criteria) this;
        }

        public Criteria andCapGreaterThanOrEqualTo(String value) {
            addCriterion("cap >=", value, "cap");
            return (Criteria) this;
        }

        public Criteria andCapLessThan(String value) {
            addCriterion("cap <", value, "cap");
            return (Criteria) this;
        }

        public Criteria andCapLessThanOrEqualTo(String value) {
            addCriterion("cap <=", value, "cap");
            return (Criteria) this;
        }

        public Criteria andCapLike(String value) {
            addCriterion("cap like", value, "cap");
            return (Criteria) this;
        }

        public Criteria andCapNotLike(String value) {
            addCriterion("cap not like", value, "cap");
            return (Criteria) this;
        }

        public Criteria andCapIn(List<String> values) {
            addCriterion("cap in", values, "cap");
            return (Criteria) this;
        }

        public Criteria andCapNotIn(List<String> values) {
            addCriterion("cap not in", values, "cap");
            return (Criteria) this;
        }

        public Criteria andCapBetween(String value1, String value2) {
            addCriterion("cap between", value1, value2, "cap");
            return (Criteria) this;
        }

        public Criteria andCapNotBetween(String value1, String value2) {
            addCriterion("cap not between", value1, value2, "cap");
            return (Criteria) this;
        }

        public Criteria andCittaIsNull() {
            addCriterion("citta is null");
            return (Criteria) this;
        }

        public Criteria andCittaIsNotNull() {
            addCriterion("citta is not null");
            return (Criteria) this;
        }

        public Criteria andCittaEqualTo(String value) {
            addCriterion("citta =", value, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaNotEqualTo(String value) {
            addCriterion("citta <>", value, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaGreaterThan(String value) {
            addCriterion("citta >", value, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaGreaterThanOrEqualTo(String value) {
            addCriterion("citta >=", value, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaLessThan(String value) {
            addCriterion("citta <", value, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaLessThanOrEqualTo(String value) {
            addCriterion("citta <=", value, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaLike(String value) {
            addCriterion("citta like", value, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaNotLike(String value) {
            addCriterion("citta not like", value, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaIn(List<String> values) {
            addCriterion("citta in", values, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaNotIn(List<String> values) {
            addCriterion("citta not in", values, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaBetween(String value1, String value2) {
            addCriterion("citta between", value1, value2, "citta");
            return (Criteria) this;
        }

        public Criteria andCittaNotBetween(String value1, String value2) {
            addCriterion("citta not between", value1, value2, "citta");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNull() {
            addCriterion("telefono is null");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNotNull() {
            addCriterion("telefono is not null");
            return (Criteria) this;
        }

        public Criteria andTelefonoEqualTo(String value) {
            addCriterion("telefono =", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotEqualTo(String value) {
            addCriterion("telefono <>", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThan(String value) {
            addCriterion("telefono >", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
            addCriterion("telefono >=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThan(String value) {
            addCriterion("telefono <", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThanOrEqualTo(String value) {
            addCriterion("telefono <=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLike(String value) {
            addCriterion("telefono like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotLike(String value) {
            addCriterion("telefono not like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoIn(List<String> values) {
            addCriterion("telefono in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotIn(List<String> values) {
            addCriterion("telefono not in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoBetween(String value1, String value2) {
            addCriterion("telefono between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotBetween(String value1, String value2) {
            addCriterion("telefono not between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andThemeIsNull() {
            addCriterion("theme is null");
            return (Criteria) this;
        }

        public Criteria andThemeIsNotNull() {
            addCriterion("theme is not null");
            return (Criteria) this;
        }

        public Criteria andThemeEqualTo(String value) {
            addCriterion("theme =", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotEqualTo(String value) {
            addCriterion("theme <>", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeGreaterThan(String value) {
            addCriterion("theme >", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeGreaterThanOrEqualTo(String value) {
            addCriterion("theme >=", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLessThan(String value) {
            addCriterion("theme <", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLessThanOrEqualTo(String value) {
            addCriterion("theme <=", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLike(String value) {
            addCriterion("theme like", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotLike(String value) {
            addCriterion("theme not like", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeIn(List<String> values) {
            addCriterion("theme in", values, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotIn(List<String> values) {
            addCriterion("theme not in", values, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeBetween(String value1, String value2) {
            addCriterion("theme between", value1, value2, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotBetween(String value1, String value2) {
            addCriterion("theme not between", value1, value2, "theme");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiIsNull() {
            addCriterion("iva_prodotti is null");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiIsNotNull() {
            addCriterion("iva_prodotti is not null");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiEqualTo(Double value) {
            addCriterion("iva_prodotti =", value, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiNotEqualTo(Double value) {
            addCriterion("iva_prodotti <>", value, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiGreaterThan(Double value) {
            addCriterion("iva_prodotti >", value, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiGreaterThanOrEqualTo(Double value) {
            addCriterion("iva_prodotti >=", value, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiLessThan(Double value) {
            addCriterion("iva_prodotti <", value, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiLessThanOrEqualTo(Double value) {
            addCriterion("iva_prodotti <=", value, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiIn(List<Double> values) {
            addCriterion("iva_prodotti in", values, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiNotIn(List<Double> values) {
            addCriterion("iva_prodotti not in", values, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiBetween(Double value1, Double value2) {
            addCriterion("iva_prodotti between", value1, value2, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaProdottiNotBetween(Double value1, Double value2) {
            addCriterion("iva_prodotti not between", value1, value2, "ivaProdotti");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniIsNull() {
            addCriterion("iva_prestazioni is null");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniIsNotNull() {
            addCriterion("iva_prestazioni is not null");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniEqualTo(Double value) {
            addCriterion("iva_prestazioni =", value, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniNotEqualTo(Double value) {
            addCriterion("iva_prestazioni <>", value, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniGreaterThan(Double value) {
            addCriterion("iva_prestazioni >", value, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniGreaterThanOrEqualTo(Double value) {
            addCriterion("iva_prestazioni >=", value, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniLessThan(Double value) {
            addCriterion("iva_prestazioni <", value, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniLessThanOrEqualTo(Double value) {
            addCriterion("iva_prestazioni <=", value, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniIn(List<Double> values) {
            addCriterion("iva_prestazioni in", values, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniNotIn(List<Double> values) {
            addCriterion("iva_prestazioni not in", values, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniBetween(Double value1, Double value2) {
            addCriterion("iva_prestazioni between", value1, value2, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andIvaPrestazioniNotBetween(Double value1, Double value2) {
            addCriterion("iva_prestazioni not between", value1, value2, "ivaPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiIsNull() {
            addCriterion("listino_prodotti is null");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiIsNotNull() {
            addCriterion("listino_prodotti is not null");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiEqualTo(Integer value) {
            addCriterion("listino_prodotti =", value, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiNotEqualTo(Integer value) {
            addCriterion("listino_prodotti <>", value, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiGreaterThan(Integer value) {
            addCriterion("listino_prodotti >", value, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiGreaterThanOrEqualTo(Integer value) {
            addCriterion("listino_prodotti >=", value, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiLessThan(Integer value) {
            addCriterion("listino_prodotti <", value, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiLessThanOrEqualTo(Integer value) {
            addCriterion("listino_prodotti <=", value, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiIn(List<Integer> values) {
            addCriterion("listino_prodotti in", values, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiNotIn(List<Integer> values) {
            addCriterion("listino_prodotti not in", values, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiBetween(Integer value1, Integer value2) {
            addCriterion("listino_prodotti between", value1, value2, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoProdottiNotBetween(Integer value1, Integer value2) {
            addCriterion("listino_prodotti not between", value1, value2, "listinoProdotti");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniIsNull() {
            addCriterion("listino_prestazioni is null");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniIsNotNull() {
            addCriterion("listino_prestazioni is not null");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniEqualTo(Integer value) {
            addCriterion("listino_prestazioni =", value, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniNotEqualTo(Integer value) {
            addCriterion("listino_prestazioni <>", value, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniGreaterThan(Integer value) {
            addCriterion("listino_prestazioni >", value, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniGreaterThanOrEqualTo(Integer value) {
            addCriterion("listino_prestazioni >=", value, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniLessThan(Integer value) {
            addCriterion("listino_prestazioni <", value, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniLessThanOrEqualTo(Integer value) {
            addCriterion("listino_prestazioni <=", value, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniIn(List<Integer> values) {
            addCriterion("listino_prestazioni in", values, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniNotIn(List<Integer> values) {
            addCriterion("listino_prestazioni not in", values, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniBetween(Integer value1, Integer value2) {
            addCriterion("listino_prestazioni between", value1, value2, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andListinoPrestazioniNotBetween(Integer value1, Integer value2) {
            addCriterion("listino_prestazioni not between", value1, value2, "listinoPrestazioni");
            return (Criteria) this;
        }

        public Criteria andRagioneSocialeLikeInsensitive(String value) {
            addCriterion("upper(ragione_sociale) like", value.toUpperCase(), "ragioneSociale");
            return (Criteria) this;
        }

        public Criteria andPivaCfLikeInsensitive(String value) {
            addCriterion("upper(piva_cf) like", value.toUpperCase(), "pivaCf");
            return (Criteria) this;
        }

        public Criteria andIndirizzoLikeInsensitive(String value) {
            addCriterion("upper(indirizzo) like", value.toUpperCase(), "indirizzo");
            return (Criteria) this;
        }

        public Criteria andCapLikeInsensitive(String value) {
            addCriterion("upper(cap) like", value.toUpperCase(), "cap");
            return (Criteria) this;
        }

        public Criteria andCittaLikeInsensitive(String value) {
            addCriterion("upper(citta) like", value.toUpperCase(), "citta");
            return (Criteria) this;
        }

        public Criteria andTelefonoLikeInsensitive(String value) {
            addCriterion("upper(telefono) like", value.toUpperCase(), "telefono");
            return (Criteria) this;
        }

        public Criteria andEmailLikeInsensitive(String value) {
            addCriterion("upper(email) like", value.toUpperCase(), "email");
            return (Criteria) this;
        }

        public Criteria andThemeLikeInsensitive(String value) {
            addCriterion("upper(theme) like", value.toUpperCase(), "theme");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application_properties
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 26 22:23:46 CET 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}