package it.aesposito.jstore.bean;

public class ApplicationPropertiesWithBLOBs extends ApplicationProperties {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.logo
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private byte[] logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.logo_stampa
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private byte[] logoStampa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.logo
     *
     * @return the value of application_properties.logo
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public byte[] getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.logo
     *
     * @param logo the value for application_properties.logo
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.logo_stampa
     *
     * @return the value of application_properties.logo_stampa
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public byte[] getLogoStampa() {
        return logoStampa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.logo_stampa
     *
     * @param logoStampa the value for application_properties.logo_stampa
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setLogoStampa(byte[] logoStampa) {
        this.logoStampa = logoStampa;
    }
}