package it.aesposito.jstore.bean;

public class ApplicationProperties {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.id
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.ragione_sociale
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private String ragioneSociale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.piva_cf
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private String pivaCf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.indirizzo
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private String indirizzo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.cap
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private String cap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.citta
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private String citta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.telefono
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private String telefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.email
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.theme
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.iva_prodotti
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private Double ivaProdotti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.iva_prestazioni
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private Double ivaPrestazioni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.listino_prodotti
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private Integer listinoProdotti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_properties.listino_prestazioni
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    private Integer listinoPrestazioni;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.id
     *
     * @return the value of application_properties.id
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.id
     *
     * @param id the value for application_properties.id
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.ragione_sociale
     *
     * @return the value of application_properties.ragione_sociale
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getRagioneSociale() {
        return ragioneSociale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.ragione_sociale
     *
     * @param ragioneSociale the value for application_properties.ragione_sociale
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setRagioneSociale(String ragioneSociale) {
        this.ragioneSociale = ragioneSociale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.piva_cf
     *
     * @return the value of application_properties.piva_cf
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getPivaCf() {
        return pivaCf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.piva_cf
     *
     * @param pivaCf the value for application_properties.piva_cf
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setPivaCf(String pivaCf) {
        this.pivaCf = pivaCf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.indirizzo
     *
     * @return the value of application_properties.indirizzo
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getIndirizzo() {
        return indirizzo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.indirizzo
     *
     * @param indirizzo the value for application_properties.indirizzo
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.cap
     *
     * @return the value of application_properties.cap
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getCap() {
        return cap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.cap
     *
     * @param cap the value for application_properties.cap
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setCap(String cap) {
        this.cap = cap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.citta
     *
     * @return the value of application_properties.citta
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getCitta() {
        return citta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.citta
     *
     * @param citta the value for application_properties.citta
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setCitta(String citta) {
        this.citta = citta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.telefono
     *
     * @return the value of application_properties.telefono
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.telefono
     *
     * @param telefono the value for application_properties.telefono
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.email
     *
     * @return the value of application_properties.email
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.email
     *
     * @param email the value for application_properties.email
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.theme
     *
     * @return the value of application_properties.theme
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.theme
     *
     * @param theme the value for application_properties.theme
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.iva_prodotti
     *
     * @return the value of application_properties.iva_prodotti
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public Double getIvaProdotti() {
        return ivaProdotti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.iva_prodotti
     *
     * @param ivaProdotti the value for application_properties.iva_prodotti
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setIvaProdotti(Double ivaProdotti) {
        this.ivaProdotti = ivaProdotti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.iva_prestazioni
     *
     * @return the value of application_properties.iva_prestazioni
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public Double getIvaPrestazioni() {
        return ivaPrestazioni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.iva_prestazioni
     *
     * @param ivaPrestazioni the value for application_properties.iva_prestazioni
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setIvaPrestazioni(Double ivaPrestazioni) {
        this.ivaPrestazioni = ivaPrestazioni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.listino_prodotti
     *
     * @return the value of application_properties.listino_prodotti
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public Integer getListinoProdotti() {
        return listinoProdotti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.listino_prodotti
     *
     * @param listinoProdotti the value for application_properties.listino_prodotti
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setListinoProdotti(Integer listinoProdotti) {
        this.listinoProdotti = listinoProdotti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_properties.listino_prestazioni
     *
     * @return the value of application_properties.listino_prestazioni
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public Integer getListinoPrestazioni() {
        return listinoPrestazioni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_properties.listino_prestazioni
     *
     * @param listinoPrestazioni the value for application_properties.listino_prestazioni
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    public void setListinoPrestazioni(Integer listinoPrestazioni) {
        this.listinoPrestazioni = listinoPrestazioni;
    }
}