package it.aesposito.jstore.bean;

import java.util.Date;

public class Articoli {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer tipologiaArticolo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.giacenza
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer giacenza;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String codice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String descrizione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.scarsita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer scarsita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.importo_unitario
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double importoUnitario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.fornitore
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer fornitore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double iva;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.categoria
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer categoria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.dtm_ins
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Date dtmIns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.dtm_mod
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Date dtmMod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articoli.note
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.id
     *
     * @return the value of articoli.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.id
     *
     * @param id the value for articoli.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.tipologia_articolo
     *
     * @return the value of articoli.tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getTipologiaArticolo() {
        return tipologiaArticolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.tipologia_articolo
     *
     * @param tipologiaArticolo the value for articoli.tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setTipologiaArticolo(Integer tipologiaArticolo) {
        this.tipologiaArticolo = tipologiaArticolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.giacenza
     *
     * @return the value of articoli.giacenza
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getGiacenza() {
        return giacenza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.giacenza
     *
     * @param giacenza the value for articoli.giacenza
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setGiacenza(Integer giacenza) {
        this.giacenza = giacenza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.codice
     *
     * @return the value of articoli.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getCodice() {
        return codice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.codice
     *
     * @param codice the value for articoli.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setCodice(String codice) {
        this.codice = codice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.descrizione
     *
     * @return the value of articoli.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.descrizione
     *
     * @param descrizione the value for articoli.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.scarsita
     *
     * @return the value of articoli.scarsita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getScarsita() {
        return scarsita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.scarsita
     *
     * @param scarsita the value for articoli.scarsita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setScarsita(Integer scarsita) {
        this.scarsita = scarsita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.importo_unitario
     *
     * @return the value of articoli.importo_unitario
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getImportoUnitario() {
        return importoUnitario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.importo_unitario
     *
     * @param importoUnitario the value for articoli.importo_unitario
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setImportoUnitario(Double importoUnitario) {
        this.importoUnitario = importoUnitario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.fornitore
     *
     * @return the value of articoli.fornitore
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getFornitore() {
        return fornitore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.fornitore
     *
     * @param fornitore the value for articoli.fornitore
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setFornitore(Integer fornitore) {
        this.fornitore = fornitore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.iva
     *
     * @return the value of articoli.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getIva() {
        return iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.iva
     *
     * @param iva the value for articoli.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setIva(Double iva) {
        this.iva = iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.categoria
     *
     * @return the value of articoli.categoria
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getCategoria() {
        return categoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.categoria
     *
     * @param categoria the value for articoli.categoria
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setCategoria(Integer categoria) {
        this.categoria = categoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.dtm_ins
     *
     * @return the value of articoli.dtm_ins
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Date getDtmIns() {
        return dtmIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.dtm_ins
     *
     * @param dtmIns the value for articoli.dtm_ins
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDtmIns(Date dtmIns) {
        this.dtmIns = dtmIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.dtm_mod
     *
     * @return the value of articoli.dtm_mod
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Date getDtmMod() {
        return dtmMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.dtm_mod
     *
     * @param dtmMod the value for articoli.dtm_mod
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDtmMod(Date dtmMod) {
        this.dtmMod = dtmMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articoli.note
     *
     * @return the value of articoli.note
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articoli.note
     *
     * @param note the value for articoli.note
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setNote(String note) {
        this.note = note;
    }
}