package it.aesposito.jstore.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticoliExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public ArticoliExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloIsNull() {
            addCriterion("tipologia_articolo is null");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloIsNotNull() {
            addCriterion("tipologia_articolo is not null");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloEqualTo(Integer value) {
            addCriterion("tipologia_articolo =", value, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloNotEqualTo(Integer value) {
            addCriterion("tipologia_articolo <>", value, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloGreaterThan(Integer value) {
            addCriterion("tipologia_articolo >", value, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloGreaterThanOrEqualTo(Integer value) {
            addCriterion("tipologia_articolo >=", value, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloLessThan(Integer value) {
            addCriterion("tipologia_articolo <", value, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloLessThanOrEqualTo(Integer value) {
            addCriterion("tipologia_articolo <=", value, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloIn(List<Integer> values) {
            addCriterion("tipologia_articolo in", values, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloNotIn(List<Integer> values) {
            addCriterion("tipologia_articolo not in", values, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloBetween(Integer value1, Integer value2) {
            addCriterion("tipologia_articolo between", value1, value2, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andTipologiaArticoloNotBetween(Integer value1, Integer value2) {
            addCriterion("tipologia_articolo not between", value1, value2, "tipologiaArticolo");
            return (Criteria) this;
        }

        public Criteria andGiacenzaIsNull() {
            addCriterion("giacenza is null");
            return (Criteria) this;
        }

        public Criteria andGiacenzaIsNotNull() {
            addCriterion("giacenza is not null");
            return (Criteria) this;
        }

        public Criteria andGiacenzaEqualTo(Integer value) {
            addCriterion("giacenza =", value, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaNotEqualTo(Integer value) {
            addCriterion("giacenza <>", value, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaGreaterThan(Integer value) {
            addCriterion("giacenza >", value, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaGreaterThanOrEqualTo(Integer value) {
            addCriterion("giacenza >=", value, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaLessThan(Integer value) {
            addCriterion("giacenza <", value, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaLessThanOrEqualTo(Integer value) {
            addCriterion("giacenza <=", value, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaIn(List<Integer> values) {
            addCriterion("giacenza in", values, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaNotIn(List<Integer> values) {
            addCriterion("giacenza not in", values, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaBetween(Integer value1, Integer value2) {
            addCriterion("giacenza between", value1, value2, "giacenza");
            return (Criteria) this;
        }

        public Criteria andGiacenzaNotBetween(Integer value1, Integer value2) {
            addCriterion("giacenza not between", value1, value2, "giacenza");
            return (Criteria) this;
        }

        public Criteria andCodiceIsNull() {
            addCriterion("codice is null");
            return (Criteria) this;
        }

        public Criteria andCodiceIsNotNull() {
            addCriterion("codice is not null");
            return (Criteria) this;
        }

        public Criteria andCodiceEqualTo(String value) {
            addCriterion("codice =", value, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceNotEqualTo(String value) {
            addCriterion("codice <>", value, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceGreaterThan(String value) {
            addCriterion("codice >", value, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceGreaterThanOrEqualTo(String value) {
            addCriterion("codice >=", value, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceLessThan(String value) {
            addCriterion("codice <", value, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceLessThanOrEqualTo(String value) {
            addCriterion("codice <=", value, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceLike(String value) {
            addCriterion("codice like", value, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceNotLike(String value) {
            addCriterion("codice not like", value, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceIn(List<String> values) {
            addCriterion("codice in", values, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceNotIn(List<String> values) {
            addCriterion("codice not in", values, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceBetween(String value1, String value2) {
            addCriterion("codice between", value1, value2, "codice");
            return (Criteria) this;
        }

        public Criteria andCodiceNotBetween(String value1, String value2) {
            addCriterion("codice not between", value1, value2, "codice");
            return (Criteria) this;
        }

        public Criteria andDescrizioneIsNull() {
            addCriterion("descrizione is null");
            return (Criteria) this;
        }

        public Criteria andDescrizioneIsNotNull() {
            addCriterion("descrizione is not null");
            return (Criteria) this;
        }

        public Criteria andDescrizioneEqualTo(String value) {
            addCriterion("descrizione =", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneNotEqualTo(String value) {
            addCriterion("descrizione <>", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneGreaterThan(String value) {
            addCriterion("descrizione >", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneGreaterThanOrEqualTo(String value) {
            addCriterion("descrizione >=", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneLessThan(String value) {
            addCriterion("descrizione <", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneLessThanOrEqualTo(String value) {
            addCriterion("descrizione <=", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneLike(String value) {
            addCriterion("descrizione like", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneNotLike(String value) {
            addCriterion("descrizione not like", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneIn(List<String> values) {
            addCriterion("descrizione in", values, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneNotIn(List<String> values) {
            addCriterion("descrizione not in", values, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneBetween(String value1, String value2) {
            addCriterion("descrizione between", value1, value2, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneNotBetween(String value1, String value2) {
            addCriterion("descrizione not between", value1, value2, "descrizione");
            return (Criteria) this;
        }

        public Criteria andScarsitaIsNull() {
            addCriterion("scarsita is null");
            return (Criteria) this;
        }

        public Criteria andScarsitaIsNotNull() {
            addCriterion("scarsita is not null");
            return (Criteria) this;
        }

        public Criteria andScarsitaEqualTo(Integer value) {
            addCriterion("scarsita =", value, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaNotEqualTo(Integer value) {
            addCriterion("scarsita <>", value, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaGreaterThan(Integer value) {
            addCriterion("scarsita >", value, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaGreaterThanOrEqualTo(Integer value) {
            addCriterion("scarsita >=", value, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaLessThan(Integer value) {
            addCriterion("scarsita <", value, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaLessThanOrEqualTo(Integer value) {
            addCriterion("scarsita <=", value, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaIn(List<Integer> values) {
            addCriterion("scarsita in", values, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaNotIn(List<Integer> values) {
            addCriterion("scarsita not in", values, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaBetween(Integer value1, Integer value2) {
            addCriterion("scarsita between", value1, value2, "scarsita");
            return (Criteria) this;
        }

        public Criteria andScarsitaNotBetween(Integer value1, Integer value2) {
            addCriterion("scarsita not between", value1, value2, "scarsita");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioIsNull() {
            addCriterion("importo_unitario is null");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioIsNotNull() {
            addCriterion("importo_unitario is not null");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioEqualTo(Double value) {
            addCriterion("importo_unitario =", value, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioNotEqualTo(Double value) {
            addCriterion("importo_unitario <>", value, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioGreaterThan(Double value) {
            addCriterion("importo_unitario >", value, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioGreaterThanOrEqualTo(Double value) {
            addCriterion("importo_unitario >=", value, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioLessThan(Double value) {
            addCriterion("importo_unitario <", value, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioLessThanOrEqualTo(Double value) {
            addCriterion("importo_unitario <=", value, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioIn(List<Double> values) {
            addCriterion("importo_unitario in", values, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioNotIn(List<Double> values) {
            addCriterion("importo_unitario not in", values, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioBetween(Double value1, Double value2) {
            addCriterion("importo_unitario between", value1, value2, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andImportoUnitarioNotBetween(Double value1, Double value2) {
            addCriterion("importo_unitario not between", value1, value2, "importoUnitario");
            return (Criteria) this;
        }

        public Criteria andFornitoreIsNull() {
            addCriterion("fornitore is null");
            return (Criteria) this;
        }

        public Criteria andFornitoreIsNotNull() {
            addCriterion("fornitore is not null");
            return (Criteria) this;
        }

        public Criteria andFornitoreEqualTo(Integer value) {
            addCriterion("fornitore =", value, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreNotEqualTo(Integer value) {
            addCriterion("fornitore <>", value, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreGreaterThan(Integer value) {
            addCriterion("fornitore >", value, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("fornitore >=", value, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreLessThan(Integer value) {
            addCriterion("fornitore <", value, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreLessThanOrEqualTo(Integer value) {
            addCriterion("fornitore <=", value, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreIn(List<Integer> values) {
            addCriterion("fornitore in", values, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreNotIn(List<Integer> values) {
            addCriterion("fornitore not in", values, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreBetween(Integer value1, Integer value2) {
            addCriterion("fornitore between", value1, value2, "fornitore");
            return (Criteria) this;
        }

        public Criteria andFornitoreNotBetween(Integer value1, Integer value2) {
            addCriterion("fornitore not between", value1, value2, "fornitore");
            return (Criteria) this;
        }

        public Criteria andIvaIsNull() {
            addCriterion("iva is null");
            return (Criteria) this;
        }

        public Criteria andIvaIsNotNull() {
            addCriterion("iva is not null");
            return (Criteria) this;
        }

        public Criteria andIvaEqualTo(Double value) {
            addCriterion("iva =", value, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaNotEqualTo(Double value) {
            addCriterion("iva <>", value, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaGreaterThan(Double value) {
            addCriterion("iva >", value, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaGreaterThanOrEqualTo(Double value) {
            addCriterion("iva >=", value, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaLessThan(Double value) {
            addCriterion("iva <", value, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaLessThanOrEqualTo(Double value) {
            addCriterion("iva <=", value, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaIn(List<Double> values) {
            addCriterion("iva in", values, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaNotIn(List<Double> values) {
            addCriterion("iva not in", values, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaBetween(Double value1, Double value2) {
            addCriterion("iva between", value1, value2, "iva");
            return (Criteria) this;
        }

        public Criteria andIvaNotBetween(Double value1, Double value2) {
            addCriterion("iva not between", value1, value2, "iva");
            return (Criteria) this;
        }

        public Criteria andCategoriaIsNull() {
            addCriterion("categoria is null");
            return (Criteria) this;
        }

        public Criteria andCategoriaIsNotNull() {
            addCriterion("categoria is not null");
            return (Criteria) this;
        }

        public Criteria andCategoriaEqualTo(Integer value) {
            addCriterion("categoria =", value, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaNotEqualTo(Integer value) {
            addCriterion("categoria <>", value, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaGreaterThan(Integer value) {
            addCriterion("categoria >", value, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaGreaterThanOrEqualTo(Integer value) {
            addCriterion("categoria >=", value, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaLessThan(Integer value) {
            addCriterion("categoria <", value, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaLessThanOrEqualTo(Integer value) {
            addCriterion("categoria <=", value, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaIn(List<Integer> values) {
            addCriterion("categoria in", values, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaNotIn(List<Integer> values) {
            addCriterion("categoria not in", values, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaBetween(Integer value1, Integer value2) {
            addCriterion("categoria between", value1, value2, "categoria");
            return (Criteria) this;
        }

        public Criteria andCategoriaNotBetween(Integer value1, Integer value2) {
            addCriterion("categoria not between", value1, value2, "categoria");
            return (Criteria) this;
        }

        public Criteria andDtmInsIsNull() {
            addCriterion("dtm_ins is null");
            return (Criteria) this;
        }

        public Criteria andDtmInsIsNotNull() {
            addCriterion("dtm_ins is not null");
            return (Criteria) this;
        }

        public Criteria andDtmInsEqualTo(Date value) {
            addCriterion("dtm_ins =", value, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsNotEqualTo(Date value) {
            addCriterion("dtm_ins <>", value, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsGreaterThan(Date value) {
            addCriterion("dtm_ins >", value, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsGreaterThanOrEqualTo(Date value) {
            addCriterion("dtm_ins >=", value, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsLessThan(Date value) {
            addCriterion("dtm_ins <", value, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsLessThanOrEqualTo(Date value) {
            addCriterion("dtm_ins <=", value, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsIn(List<Date> values) {
            addCriterion("dtm_ins in", values, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsNotIn(List<Date> values) {
            addCriterion("dtm_ins not in", values, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsBetween(Date value1, Date value2) {
            addCriterion("dtm_ins between", value1, value2, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmInsNotBetween(Date value1, Date value2) {
            addCriterion("dtm_ins not between", value1, value2, "dtmIns");
            return (Criteria) this;
        }

        public Criteria andDtmModIsNull() {
            addCriterion("dtm_mod is null");
            return (Criteria) this;
        }

        public Criteria andDtmModIsNotNull() {
            addCriterion("dtm_mod is not null");
            return (Criteria) this;
        }

        public Criteria andDtmModEqualTo(Date value) {
            addCriterion("dtm_mod =", value, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModNotEqualTo(Date value) {
            addCriterion("dtm_mod <>", value, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModGreaterThan(Date value) {
            addCriterion("dtm_mod >", value, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModGreaterThanOrEqualTo(Date value) {
            addCriterion("dtm_mod >=", value, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModLessThan(Date value) {
            addCriterion("dtm_mod <", value, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModLessThanOrEqualTo(Date value) {
            addCriterion("dtm_mod <=", value, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModIn(List<Date> values) {
            addCriterion("dtm_mod in", values, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModNotIn(List<Date> values) {
            addCriterion("dtm_mod not in", values, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModBetween(Date value1, Date value2) {
            addCriterion("dtm_mod between", value1, value2, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andDtmModNotBetween(Date value1, Date value2) {
            addCriterion("dtm_mod not between", value1, value2, "dtmMod");
            return (Criteria) this;
        }

        public Criteria andCodiceLikeInsensitive(String value) {
            addCriterion("upper(codice) like", value.toUpperCase(), "codice");
            return (Criteria) this;
        }

        public Criteria andDescrizioneLikeInsensitive(String value) {
            addCriterion("upper(descrizione) like", value.toUpperCase(), "descrizione");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table articoli
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 26 22:23:47 CET 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}