package it.aesposito.jstore.bean;

public class ArticoloListino {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_listino.id
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_listino.articolo
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    private Integer articolo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_listino.listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    private Integer listino;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_listino.id
     *
     * @return the value of articolo_listino.id
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_listino.id
     *
     * @param id the value for articolo_listino.id
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_listino.articolo
     *
     * @return the value of articolo_listino.articolo
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    public Integer getArticolo() {
        return articolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_listino.articolo
     *
     * @param articolo the value for articolo_listino.articolo
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    public void setArticolo(Integer articolo) {
        this.articolo = articolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_listino.listino
     *
     * @return the value of articolo_listino.listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    public Integer getListino() {
        return listino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_listino.listino
     *
     * @param listino the value for articolo_listino.listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    public void setListino(Integer listino) {
        this.listino = listino;
    }
}