package it.aesposito.jstore.bean;

public class ArticoloFattura {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_fattura.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_fattura.articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer articolo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_fattura.fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer fattura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_fattura.listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer listino;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_fattura.quantita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer quantita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_fattura.imponibile
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double imponibile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_fattura.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double iva;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articolo_fattura.importo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double importo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_fattura.id
     *
     * @return the value of articolo_fattura.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_fattura.id
     *
     * @param id the value for articolo_fattura.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_fattura.articolo
     *
     * @return the value of articolo_fattura.articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getArticolo() {
        return articolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_fattura.articolo
     *
     * @param articolo the value for articolo_fattura.articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setArticolo(Integer articolo) {
        this.articolo = articolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_fattura.fattura
     *
     * @return the value of articolo_fattura.fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getFattura() {
        return fattura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_fattura.fattura
     *
     * @param fattura the value for articolo_fattura.fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setFattura(Integer fattura) {
        this.fattura = fattura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_fattura.listino
     *
     * @return the value of articolo_fattura.listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getListino() {
        return listino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_fattura.listino
     *
     * @param listino the value for articolo_fattura.listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setListino(Integer listino) {
        this.listino = listino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_fattura.quantita
     *
     * @return the value of articolo_fattura.quantita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getQuantita() {
        return quantita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_fattura.quantita
     *
     * @param quantita the value for articolo_fattura.quantita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setQuantita(Integer quantita) {
        this.quantita = quantita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_fattura.imponibile
     *
     * @return the value of articolo_fattura.imponibile
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getImponibile() {
        return imponibile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_fattura.imponibile
     *
     * @param imponibile the value for articolo_fattura.imponibile
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setImponibile(Double imponibile) {
        this.imponibile = imponibile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_fattura.iva
     *
     * @return the value of articolo_fattura.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getIva() {
        return iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_fattura.iva
     *
     * @param iva the value for articolo_fattura.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setIva(Double iva) {
        this.iva = iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articolo_fattura.importo
     *
     * @return the value of articolo_fattura.importo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getImporto() {
        return importo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articolo_fattura.importo
     *
     * @param importo the value for articolo_fattura.importo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setImporto(Double importo) {
        this.importo = importo;
    }
}