package it.aesposito.jstore.bean;

public class Categorie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorie.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorie.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String descrizione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorie.tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer tipologiaArticolo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorie.id
     *
     * @return the value of categorie.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorie.id
     *
     * @param id the value for categorie.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorie.descrizione
     *
     * @return the value of categorie.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorie.descrizione
     *
     * @param descrizione the value for categorie.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorie.tipologia_articolo
     *
     * @return the value of categorie.tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getTipologiaArticolo() {
        return tipologiaArticolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorie.tipologia_articolo
     *
     * @param tipologiaArticolo the value for categorie.tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setTipologiaArticolo(Integer tipologiaArticolo) {
        this.tipologiaArticolo = tipologiaArticolo;
    }
}