package it.aesposito.jstore.bean;

import java.util.Date;

public class Fatture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fatture.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fatture.numero
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer numero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fatture.anno
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer anno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fatture.totale
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double totale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fatture.imponibile
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double imponibile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fatture.dtm_emissione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Date dtmEmissione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fatture.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double iva;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fatture.dtm_modifica
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Date dtmModifica;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fatture.id
     *
     * @return the value of fatture.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fatture.id
     *
     * @param id the value for fatture.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fatture.numero
     *
     * @return the value of fatture.numero
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getNumero() {
        return numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fatture.numero
     *
     * @param numero the value for fatture.numero
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fatture.anno
     *
     * @return the value of fatture.anno
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getAnno() {
        return anno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fatture.anno
     *
     * @param anno the value for fatture.anno
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setAnno(Integer anno) {
        this.anno = anno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fatture.totale
     *
     * @return the value of fatture.totale
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getTotale() {
        return totale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fatture.totale
     *
     * @param totale the value for fatture.totale
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setTotale(Double totale) {
        this.totale = totale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fatture.imponibile
     *
     * @return the value of fatture.imponibile
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getImponibile() {
        return imponibile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fatture.imponibile
     *
     * @param imponibile the value for fatture.imponibile
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setImponibile(Double imponibile) {
        this.imponibile = imponibile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fatture.dtm_emissione
     *
     * @return the value of fatture.dtm_emissione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Date getDtmEmissione() {
        return dtmEmissione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fatture.dtm_emissione
     *
     * @param dtmEmissione the value for fatture.dtm_emissione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDtmEmissione(Date dtmEmissione) {
        this.dtmEmissione = dtmEmissione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fatture.iva
     *
     * @return the value of fatture.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getIva() {
        return iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fatture.iva
     *
     * @param iva the value for fatture.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setIva(Double iva) {
        this.iva = iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fatture.dtm_modifica
     *
     * @return the value of fatture.dtm_modifica
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Date getDtmModifica() {
        return dtmModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fatture.dtm_modifica
     *
     * @param dtmModifica the value for fatture.dtm_modifica
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDtmModifica(Date dtmModifica) {
        this.dtmModifica = dtmModifica;
    }
}