package it.aesposito.jstore.bean;

public class Fornitori {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String codice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.ragione_sociale
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String ragioneSociale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.piva_cf
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String pivaCf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.indirizzo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String indirizzo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.citta
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String citta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.cap
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String cap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.telefono
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String telefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fornitori.email
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private byte[] email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.id
     *
     * @return the value of fornitori.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.id
     *
     * @param id the value for fornitori.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.codice
     *
     * @return the value of fornitori.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getCodice() {
        return codice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.codice
     *
     * @param codice the value for fornitori.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setCodice(String codice) {
        this.codice = codice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.ragione_sociale
     *
     * @return the value of fornitori.ragione_sociale
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getRagioneSociale() {
        return ragioneSociale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.ragione_sociale
     *
     * @param ragioneSociale the value for fornitori.ragione_sociale
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setRagioneSociale(String ragioneSociale) {
        this.ragioneSociale = ragioneSociale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.piva_cf
     *
     * @return the value of fornitori.piva_cf
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getPivaCf() {
        return pivaCf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.piva_cf
     *
     * @param pivaCf the value for fornitori.piva_cf
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setPivaCf(String pivaCf) {
        this.pivaCf = pivaCf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.indirizzo
     *
     * @return the value of fornitori.indirizzo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getIndirizzo() {
        return indirizzo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.indirizzo
     *
     * @param indirizzo the value for fornitori.indirizzo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.citta
     *
     * @return the value of fornitori.citta
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getCitta() {
        return citta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.citta
     *
     * @param citta the value for fornitori.citta
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setCitta(String citta) {
        this.citta = citta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.cap
     *
     * @return the value of fornitori.cap
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getCap() {
        return cap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.cap
     *
     * @param cap the value for fornitori.cap
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setCap(String cap) {
        this.cap = cap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.telefono
     *
     * @return the value of fornitori.telefono
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.telefono
     *
     * @param telefono the value for fornitori.telefono
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fornitori.email
     *
     * @return the value of fornitori.email
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public byte[] getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fornitori.email
     *
     * @param email the value for fornitori.email
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setEmail(byte[] email) {
        this.email = email;
    }
}