package it.aesposito.jstore.bean;

public class Iva {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iva.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iva.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String descrizione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iva.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double iva;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iva.id
     *
     * @return the value of iva.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iva.id
     *
     * @param id the value for iva.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iva.descrizione
     *
     * @return the value of iva.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iva.descrizione
     *
     * @param descrizione the value for iva.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iva.iva
     *
     * @return the value of iva.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getIva() {
        return iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iva.iva
     *
     * @param iva the value for iva.iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setIva(Double iva) {
        this.iva = iva;
    }
}