package it.aesposito.jstore.bean;

public class Listino {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listino.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listino.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String descrizione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listino.ricarico
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Double ricarico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listino.tipologia_listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer tipologiaListino;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listino.id
     *
     * @return the value of listino.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listino.id
     *
     * @param id the value for listino.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listino.descrizione
     *
     * @return the value of listino.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listino.descrizione
     *
     * @param descrizione the value for listino.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listino.ricarico
     *
     * @return the value of listino.ricarico
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Double getRicarico() {
        return ricarico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listino.ricarico
     *
     * @param ricarico the value for listino.ricarico
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setRicarico(Double ricarico) {
        this.ricarico = ricarico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listino.tipologia_listino
     *
     * @return the value of listino.tipologia_listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getTipologiaListino() {
        return tipologiaListino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listino.tipologia_listino
     *
     * @param tipologiaListino the value for listino.tipologia_listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setTipologiaListino(Integer tipologiaListino) {
        this.tipologiaListino = tipologiaListino;
    }
}