package it.aesposito.jstore.bean;

public class TipologiaArticolo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipologia_articolo.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipologia_articolo.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String descrizione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipologia_articolo.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private String codice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipologia_articolo.considera_quantita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Byte consideraQuantita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipologia_articolo.considera_fornitore
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    private Byte consideraFornitore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipologia_articolo.id
     *
     * @return the value of tipologia_articolo.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipologia_articolo.id
     *
     * @param id the value for tipologia_articolo.id
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipologia_articolo.descrizione
     *
     * @return the value of tipologia_articolo.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipologia_articolo.descrizione
     *
     * @param descrizione the value for tipologia_articolo.descrizione
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipologia_articolo.codice
     *
     * @return the value of tipologia_articolo.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public String getCodice() {
        return codice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipologia_articolo.codice
     *
     * @param codice the value for tipologia_articolo.codice
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setCodice(String codice) {
        this.codice = codice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipologia_articolo.considera_quantita
     *
     * @return the value of tipologia_articolo.considera_quantita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Byte getConsideraQuantita() {
        return consideraQuantita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipologia_articolo.considera_quantita
     *
     * @param consideraQuantita the value for tipologia_articolo.considera_quantita
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setConsideraQuantita(Byte consideraQuantita) {
        this.consideraQuantita = consideraQuantita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipologia_articolo.considera_fornitore
     *
     * @return the value of tipologia_articolo.considera_fornitore
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public Byte getConsideraFornitore() {
        return consideraFornitore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipologia_articolo.considera_fornitore
     *
     * @param consideraFornitore the value for tipologia_articolo.considera_fornitore
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    public void setConsideraFornitore(Byte consideraFornitore) {
        this.consideraFornitore = consideraFornitore;
    }
}