/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.aesposito.forms;

import it.aesposito.application.Constants;
import static it.aesposito.application.Constants.DIALOG_POSITION;
import it.aesposito.application.Themes;
import it.aesposito.db.DB;
import it.aesposito.db.SQLMapClientFactory;
import it.aesposito.jstore.bean.ApplicationProperties;
import it.aesposito.jstore.bean.ApplicationPropertiesExample;
import it.aesposito.jstore.dao.ApplicationPropertiesMapper;
import it.aesposito.jstore.forms.AliquoteForm;
import it.aesposito.jstore.forms.ArticoloForm;
import it.aesposito.jstore.forms.CategorieForm;
import it.aesposito.jstore.forms.ListaArticoliForm;
import it.aesposito.jstore.forms.ListaCategorieForm;
import it.aesposito.jstore.forms.ListaIvaForm;
import it.aesposito.jstore.forms.ListaListiniForm;
import it.aesposito.jstore.forms.ListaPrestazioniForm;
import it.aesposito.jstore.forms.ListiniForm;
import it.aesposito.jstore.forms.PreferenzeForm;
import it.aesposito.jstore.forms.PrestazioneForm;
import it.aesposito.jstore.forms.VenditaForm;
import it.aesposito.utils.Utils;
import java.awt.Component;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import org.apache.ibatis.session.SqlSession;
import it.aesposito.jstore.forms.ListaArticoliForm.ListaArticoliOptions;
import it.aesposito.jstore.forms.ListaVenditeForm;
import it.aesposito.jstore.forms.RiepilogoVendutoForm;
import java.awt.AWTException;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
/**
 *
 * @author Antonio
 */
public class MainApplicationForm extends JFrame implements Constants {
    private Map<Integer, JPanel> openedForms = null;
    private Integer openedFormsIds = 1;
    public ListaArticoliForm listaArticoliForm;
    public ListaPrestazioniForm listaPrestazioniForm;
    public ListaCategorieForm listaCategorieForm;
    public ListaListiniForm listaListiniForm;
    public ListaIvaForm listaIvaForm;
    public VenditaForm venditaForm;
    public ListaVenditeForm listaVenditeForm;
    public RiepilogoVendutoForm riepilogoVendutoForm;
    private TrayIcon tIcon;
    
    /**
     * Creates new form MainApplicationFrame
     */
    public MainApplicationForm() {
        /*try{ 
            UIManager.setLookAndFeel(
                UIManager. getSystemLookAndFeelClassName());
        }catch(Exception e){
            e.printStackTrace();
        }*/
        initComponents();
        
        try{
            if(Utils.checkArticoloSottoScorta()){
                tIcon = new TrayIcon(Toolkit.getDefaultToolkit().getImage("./tray.png"));
                SystemTray.getSystemTray().add(tIcon);
                tIcon.displayMessage("Controllare il magazzino!", "Ci sono alcuni articoli sotto la soglia di scorta", TrayIcon.MessageType.WARNING);

                tIcon.addActionListener(new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        SystemTray.getSystemTray().remove(tIcon);

                        //jMenuItem4ActionPerformed(e);
                    }
                });

                //Utils.showInfoAlert("Attenzione! Ci sono alcuni articoli sotto la soglia di scorta");
            }
        }catch(AWTException awe){
            
        }catch(IOException ex){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem19.setText("jMenuItem19");

        jMenu3.setText("jMenu3");

        jMenuItem23.setText("jMenuItem23");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jStore Manager V1.0");
        setBackground(new java.awt.Color(158, 185, 214));
        setMinimumSize(new java.awt.Dimension(859, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(158, 185, 214));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/766.png"))); // NOI18N
        jButton1.setToolTipText("Magazzino");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/729.png"))); // NOI18N
        jButton3.setToolTipText("Prestazioni");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/557.png"))); // NOI18N
        jButton4.setToolTipText("Listini");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/593.png"))); // NOI18N
        jButton5.setToolTipText("Vendita");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton5);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/830.png"))); // NOI18N
        jButton2.setToolTipText("Preferenze");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/834.png"))); // NOI18N
        jButton6.setToolTipText("Esci");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton6);

        mainMenuBar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenu4.setText("Generali");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem6.setText("Impostazioni");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);
        jMenu4.add(jSeparator3);

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem2.setText("Esci");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        mainMenuBar.add(jMenu4);

        jMenu1.setText("Magazzino");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem4.setText("Elenco Prodotti");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem5.setText("Nuovo Prodotto");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator4);

        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem3.setText("Categorie Prodotti");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem16.setText("Nuova Categoria");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        mainMenuBar.add(jMenu1);

        jMenu2.setText("Prestazioni");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem11.setText("Elenco Prestazioni");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem10.setText("Nuova Prestazione");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);
        jMenu2.add(jSeparator5);

        jMenuItem17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem17.setText("Categorie Prestazioni");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem18.setText("Nuova Categoria");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        mainMenuBar.add(jMenu2);

        jMenu7.setText("Listini");
        jMenu7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem24.setText("Elenco Listini");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem24);

        jMenuItem25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem25.setText("Nuovo Listino");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem25);

        mainMenuBar.add(jMenu7);

        jMenu5.setText("Vendita");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem13.setText("Nuova Vendita");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem14.setText("Elenco Vendite");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        mainMenuBar.add(jMenu5);

        jMenu8.setText("Contabilità");
        jMenu8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem9.setText("Riepilogo venduto");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        mainMenuBar.add(jMenu8);

        jMenu6.setText("Iva");
        jMenu6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem20.setText("Elenco Aliquote");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem21.setText("Nuova Aliquota");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem21);

        mainMenuBar.add(jMenu6);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        manageApplicationClose(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            DB.init();
        } catch (Exception ex){
            Utils.logError(MainApplicationForm.class,ex);
            Utils.showErrorAlert("Errore nell'inizializzazione del Database");
        }
        
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        openedForms = new HashMap<Integer, JPanel>();
        
        this.addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                manageApplicationClose(e.getWindow());
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
        
    }//GEN-LAST:event_formWindowOpened

    private void manageApplicationClose(Window w){
        
        if(JOptionPane.showConfirmDialog(w, "Sei sicuro di voler uscire?", "Attenzione", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION ){
            
            SystemTray.getSystemTray().remove(tIcon);
            w.setVisible(false);
            w.dispose();

        }

    }
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        final JDialog dialog = new JDialog(this,"Elenco Articoli", true);
        listaArticoliForm = new ListaArticoliForm(dialog,openedFormsIds, this, "Elenco Articoli",null,Arrays.asList(new ListaArticoliOptions[]{ListaArticoliOptions.SCORTE_PANEL,ListaArticoliOptions.RESULT_INFO,ListaArticoliOptions.FILTRI_GIACENZA}),1);
        showDialog(dialog,listaArticoliForm);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        openArticoloForm(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        final JDialog dialog = new JDialog(this,"About", true);
        AboutForm about = new AboutForm(dialog, 0, this, "About", false, false, false, false);
        showDialog(dialog,about);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        final JDialog dialog = new JDialog(this,"Elenco Categorie Prodotti", true);
        listaCategorieForm = new ListaCategorieForm(dialog,openedFormsIds, this, "Elenco Categorie",1);
        showDialog(dialog,listaCategorieForm);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        final JDialog dialog = new JDialog(this,"Preferenze", true);
        PreferenzeForm prefs = new PreferenzeForm(dialog,this,"Preferenze",false,true,false,true,1,1);
        showDialog(dialog, prefs);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        openCategoriaForm(0,1);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        final JDialog dialog = new JDialog(this,"Gestione Aliquota", true);
        AliquoteForm iva = new AliquoteForm(dialog,this,"Gestione Aliquota",false,true,false,true,0);
        showDialog(dialog, iva);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        openCategoriaForm(0,2);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        openPrestazioneForm(0);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        final JDialog dialog = new JDialog(this,"Elenco Prestazioni", true);
        listaPrestazioniForm = new ListaPrestazioniForm(dialog,openedFormsIds, this, "Elenco Prestazioni");
        showDialog(dialog,listaPrestazioniForm);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        final JDialog dialog = new JDialog(this,"Gestione Listino", true);
        ListiniForm listino = new ListiniForm(dialog,this,"Gestione Listino",false,true,false,true,0);
        showDialog(dialog, listino);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        final JDialog dialog = new JDialog(this,"Elenco Categorie Prodotti", true);
        listaCategorieForm = new ListaCategorieForm(dialog,openedFormsIds, this, "Elenco Categorie",2);
        showDialog(dialog,listaCategorieForm);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        final JDialog dialog = new JDialog(this,"Elenco Listini", true);
        listaListiniForm = new ListaListiniForm(dialog,openedFormsIds, this, "Elenco Categorie");
        showDialog(dialog,listaListiniForm);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        final JDialog dialog = new JDialog(this,"Elenco Aliquote Iva", true);
        listaIvaForm = new ListaIvaForm(dialog,openedFormsIds, this, "Elenco Aliquote Iva");
        showDialog(dialog,listaIvaForm);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jMenuItem4ActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jMenuItem11ActionPerformed(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jMenuItem24ActionPerformed(evt);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jMenuItem13ActionPerformed(evt);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jMenuItem6ActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        manageApplicationClose(this);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        final JDialog dialog = new JDialog(this,"Vendita", true);
        venditaForm = new VenditaForm(dialog,openedFormsIds, this, "Vendita",0);
        showDialog(dialog,venditaForm);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        final JDialog dialog = new JDialog(this,"Elenco Vendite", true);
        listaVenditeForm = new ListaVenditeForm(dialog,openedFormsIds, this, "Elenco Vendite");
        showDialog(dialog, listaVenditeForm);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        final JDialog dialog = new JDialog(this,"Riepilogo venduto", true);
        riepilogoVendutoForm = new RiepilogoVendutoForm(dialog,openedFormsIds, this, "Riepilogo venduto");
        showDialog(dialog, riepilogoVendutoForm);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            
            String theme_class = "";
            
            SqlSession session = null;
            try {
                session = SQLMapClientFactory.getSqlMapClient().openSession();
            } catch (IOException ex) {
                Logger.getLogger(PreferenzeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            ApplicationPropertiesMapper apm = session.getMapper(ApplicationPropertiesMapper.class);
            ApplicationPropertiesExample ape = new ApplicationPropertiesExample();
            List<ApplicationProperties> list_props = apm.selectByExample(ape);

            if(list_props == null || list_props.size() != 1)
                theme_class = Themes.getDefaultThemeClass();
            else
                theme_class = (String) Themes.getThemes().get(list_props.get(0).getTheme());
            
            Properties props = new Properties();
            props.put("logoString", "");
            
            Class c = Class.forName(theme_class);
            Method metodo = c.getMethod("setCurrentTheme", new Class[] {Properties.class});
            metodo.invoke(null, props);
            
            UIManager.setLookAndFeel(theme_class);
            
        } catch(Exception ex){
            try{
                UIManager.setLookAndFeel(Themes.getDefaultThemeClass());
            }catch(Exception sub_ex){
            }
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainApplicationForm maf = new MainApplicationForm();
                maf.setVisible(true);
                maf.setExtendedState(maf.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            }
        });
    }
    
    public void closeRitiriForm(){
        //this.listaRitiriForm = null;
    }
    
    public void refreshChilds(){
        if(listaArticoliForm != null){
            listaArticoliForm.loadList();
            listaArticoliForm.refreshInfoComponents();
        }
        
        if(listaPrestazioniForm != null){
            listaPrestazioniForm.loadList();
            listaPrestazioniForm.refreshInfoComponents();
        }
        
        if(listaListiniForm != null)
            listaListiniForm.refreshInfoComponents();
        
        if(listaCategorieForm != null)
            listaCategorieForm.refreshInfoComponents();
        
        if(listaIvaForm != null)
            listaIvaForm.refreshInfoComponents();
        
        if(venditaForm != null)
            venditaForm.refreshInfoComponents();
        
        if(listaVenditeForm != null)
            listaVenditeForm.refreshInfoComponents();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuBar mainMenuBar;
    // End of variables declaration//GEN-END:variables

    public void openArticoloForm(int articoloId) {
        final JDialog dialog = new JDialog(this,"Gestione Articolo", true);
        ArticoloForm articoloForm = new ArticoloForm(dialog,this,articoloId);
        showDialog(dialog, articoloForm);
    }

    public void openPrestazioneForm(int prestazioneId) {
        final JDialog dialog = new JDialog(this,"Gestione Prestazione", true);
        PrestazioneForm prestazioneForm = new PrestazioneForm(dialog,this,"Gestione Prestazione",false,true,false,true,prestazioneId,openedFormsIds);
        showDialog(dialog,prestazioneForm);
    }
    
    public void openCategoriaForm(int categoriaId, Integer tipo) {
        final JDialog dialog = new JDialog(this,"Gestione Categoria", true);
        CategorieForm categoriaForm = new CategorieForm(dialog,this,"Gestione Categoria",false,true,false,true,categoriaId,tipo);
        showDialog(dialog,categoriaForm);
    }
    
    public void openListinoForm(int listinoId, Integer tipo) {
        final JDialog dialog = new JDialog(this,"Gestione Listino", true);
        ListiniForm listinoForm = new ListiniForm(dialog,this,"Gestione Listino",false,true,false,true,listinoId);
        showDialog(dialog,listinoForm);
    }
    
    public void openIvaForm(int ivaId) {
        final JDialog dialog = new JDialog(this,"Gestione Iva", true);
        AliquoteForm ivaForm = new AliquoteForm(dialog,this,"Gestione Iva",false,true,false,true,ivaId);
        showDialog(dialog,ivaForm);
    }
    
    public void openVenditaForm(int idVendita){
        final JDialog dialog = new JDialog(this,"Vendita", true);
        venditaForm = new VenditaForm(dialog,openedFormsIds, this, "Vendita",idVendita);
        showDialog(dialog,venditaForm);
    }
    
    public void closeForm(Integer formId) {
        openedForms.remove(formId);
        refreshChilds();
    }
    
    public void showDialog(final JDialog dialog, final Component c){
        dialog.setResizable(false);
        dialog.setLocation(DIALOG_POSITION);
        dialog.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        dialog.addWindowListener(new WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e){
                switch(((MySpecialForm)c).form_mode){
                    case INSERT_MODE:
                    case MODIFY_MODE:

                        if(JOptionPane.showConfirmDialog(c, "Sei sicuro di voler uscire? I dati non salvati andranno persi.","Attenzione",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                            dialog.dispose();
                        }

                        break;
                    default:
                        dialog.dispose();
                }
                
            }
        });
        
        dialog.getContentPane().add(c);
        dialog.pack();
        dialog.setVisible(true);
    }

    public void resetListaVenditeSelection() {
        if(listaVenditeForm != null)
            listaVenditeForm.resetSelection();
    }
    
}
