package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.ApplicationProperties;
import it.aesposito.jstore.bean.ApplicationPropertiesExample;
import it.aesposito.jstore.bean.ApplicationPropertiesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationPropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int countByExample(ApplicationPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int deleteByExample(ApplicationPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int insert(ApplicationPropertiesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int insertSelective(ApplicationPropertiesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    List<ApplicationPropertiesWithBLOBs> selectByExampleWithBLOBs(ApplicationPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    List<ApplicationProperties> selectByExample(ApplicationPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    ApplicationPropertiesWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int updateByExampleSelective(@Param("record") ApplicationPropertiesWithBLOBs record, @Param("example") ApplicationPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") ApplicationPropertiesWithBLOBs record, @Param("example") ApplicationPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int updateByExample(@Param("record") ApplicationProperties record, @Param("example") ApplicationPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int updateByPrimaryKeySelective(ApplicationPropertiesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(ApplicationPropertiesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_properties
     *
     * @mbggenerated Wed Mar 26 22:23:46 CET 2014
     */
    int updateByPrimaryKey(ApplicationProperties record);
}