package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.Articoli;
import it.aesposito.jstore.bean.ArticoliExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticoliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int countByExample(ArticoliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByExample(ArticoliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insert(Articoli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insertSelective(Articoli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<Articoli> selectByExampleWithBLOBs(ArticoliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<Articoli> selectByExample(ArticoliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    Articoli selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleSelective(@Param("record") Articoli record, @Param("example") ArticoliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Articoli record, @Param("example") ArticoliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExample(@Param("record") Articoli record, @Param("example") ArticoliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeySelective(Articoli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(Articoli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articoli
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKey(Articoli record);
}