package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.ArticoloListino;
import it.aesposito.jstore.bean.ArticoloListinoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticoloListinoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int countByExample(ArticoloListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int deleteByExample(ArticoloListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int insert(ArticoloListino record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int insertSelective(ArticoloListino record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    List<ArticoloListino> selectByExample(ArticoloListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    ArticoloListino selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int updateByExampleSelective(@Param("record") ArticoloListino record, @Param("example") ArticoloListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int updateByExample(@Param("record") ArticoloListino record, @Param("example") ArticoloListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int updateByPrimaryKeySelective(ArticoloListino record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_listino
     *
     * @mbggenerated Tue Mar 04 22:28:25 CET 2014
     */
    int updateByPrimaryKey(ArticoloListino record);
}