package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.ArticoloFattura;
import it.aesposito.jstore.bean.ArticoloFatturaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticoloFatturaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int countByExample(ArticoloFatturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByExample(ArticoloFatturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insert(ArticoloFattura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insertSelective(ArticoloFattura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<ArticoloFattura> selectByExample(ArticoloFatturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    ArticoloFattura selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleSelective(@Param("record") ArticoloFattura record, @Param("example") ArticoloFatturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExample(@Param("record") ArticoloFattura record, @Param("example") ArticoloFatturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeySelective(ArticoloFattura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articolo_fattura
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKey(ArticoloFattura record);
}