package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.Categorie;
import it.aesposito.jstore.bean.CategorieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategorieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int countByExample(CategorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByExample(CategorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insert(Categorie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insertSelective(Categorie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<Categorie> selectByExample(CategorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    Categorie selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleSelective(@Param("record") Categorie record, @Param("example") CategorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExample(@Param("record") Categorie record, @Param("example") CategorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeySelective(Categorie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorie
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKey(Categorie record);
}