package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.Fatture;
import it.aesposito.jstore.bean.FattureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FattureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int countByExample(FattureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByExample(FattureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insert(Fatture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insertSelective(Fatture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<Fatture> selectByExample(FattureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    Fatture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleSelective(@Param("record") Fatture record, @Param("example") FattureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExample(@Param("record") Fatture record, @Param("example") FattureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeySelective(Fatture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fatture
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKey(Fatture record);
}