package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.Fornitori;
import it.aesposito.jstore.bean.FornitoriExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FornitoriMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int countByExample(FornitoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByExample(FornitoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insert(Fornitori record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insertSelective(Fornitori record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<Fornitori> selectByExampleWithBLOBs(FornitoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<Fornitori> selectByExample(FornitoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    Fornitori selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleSelective(@Param("record") Fornitori record, @Param("example") FornitoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Fornitori record, @Param("example") FornitoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExample(@Param("record") Fornitori record, @Param("example") FornitoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeySelective(Fornitori record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(Fornitori record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fornitori
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKey(Fornitori record);
}