package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.Iva;
import it.aesposito.jstore.bean.IvaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IvaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int countByExample(IvaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByExample(IvaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insert(Iva record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insertSelective(Iva record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<Iva> selectByExample(IvaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    Iva selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleSelective(@Param("record") Iva record, @Param("example") IvaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExample(@Param("record") Iva record, @Param("example") IvaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeySelective(Iva record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iva
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKey(Iva record);
}