package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.Listino;
import it.aesposito.jstore.bean.ListinoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ListinoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int countByExample(ListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByExample(ListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insert(Listino record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insertSelective(Listino record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<Listino> selectByExample(ListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    Listino selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleSelective(@Param("record") Listino record, @Param("example") ListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExample(@Param("record") Listino record, @Param("example") ListinoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeySelective(Listino record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listino
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKey(Listino record);
}