package it.aesposito.jstore.dao;

import it.aesposito.jstore.bean.TipologiaArticolo;
import it.aesposito.jstore.bean.TipologiaArticoloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipologiaArticoloMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int countByExample(TipologiaArticoloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByExample(TipologiaArticoloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insert(TipologiaArticolo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int insertSelective(TipologiaArticolo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    List<TipologiaArticolo> selectByExample(TipologiaArticoloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    TipologiaArticolo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExampleSelective(@Param("record") TipologiaArticolo record, @Param("example") TipologiaArticoloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByExample(@Param("record") TipologiaArticolo record, @Param("example") TipologiaArticoloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKeySelective(TipologiaArticolo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipologia_articolo
     *
     * @mbggenerated Wed Mar 26 22:23:47 CET 2014
     */
    int updateByPrimaryKey(TipologiaArticolo record);
}